/** Convert an array of records to CSV and trigger a browser download. */
export function exportCsv(filename: string, rows: Record<string, unknown>[], columns?: string[]) {
  if (rows.length === 0) return;
  const cols = columns ?? Object.keys(rows[0]);
  const escape = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const csv = [cols.join(","), ...rows.map((r) => cols.map((c) => escape(r[c])).join(","))].join("\n");
  download(`${filename}.csv`, csv, "text/csv");
}

/** A simple "PDF" placeholder — downloads a text document so the action is real in demo mode. */
export function downloadPdfPlaceholder(filename: string, title: string, lines: string[]) {
  const body = [`${title}`, "=".repeat(title.length), "", ...lines, "", "— Generated by VenueFlow (demo)"].join("\n");
  download(`${filename}.txt`, body, "text/plain");
}

function download(name: string, content: string, type: string) {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: `${type};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}
